/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlertCircle: typeof import('./src/components/icons/AlertCircle.vue')['default']
    AlertTriangle: typeof import('./src/components/icons/AlertTriangle.vue')['default']
    CalendarDay: typeof import('./src/components/CalendarDay.vue')['default']
    CalendarGrid: typeof import('./src/components/CalendarGrid.vue')['default']
    CalendarHeader: typeof import('./src/components/CalendarHeader.vue')['default']
    CheckCircle: typeof import('./src/components/icons/CheckCircle.vue')['default']
      DebugInfo: typeof import('./src/components/DebugInfo.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FastingDetail: typeof import('./src/components/FastingDetail.vue')['default']
    Info: typeof import('./src/components/icons/Info.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Warning: typeof import('./src/components/icons/Warning.vue')['default']
  }
}
