name: 新功能请求
description: 提出一个新功能或改进建议
title: "[Feature] "
labels: ["功能请求"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你提出功能建议！请详细描述你的想法，这将帮助我们更好地理解和评估。

        - **提交功能请求前**：请检查 [已有 Issues](https://github.com/tabloving/SK_Calendar/issues)列表，了解是否有类似功能已被讨论或请求。这有助于我们避免重复工作，并高效地专注于改进项目。

  - type: checkboxes
    id: check-existing
    attributes:
      label: 检查现有问题和讨论
      description: 确认您在提交新请求之前已经检查了现有报告和讨论。
      options:
        - label: 我已经搜索了现有问题和讨论。
          required: true
        - label: 我正在使用最新版本的此应用。
          required: true

  - type: textarea
    id: feature-description
    attributes:
      label: 你希望添加什么功能或改进什么？
      description: 请详细描述您希望添加的功能或进行的改进。
      placeholder: 我希望可以...
    validations:
      required: true

  - type: textarea
    id: why-needed
    attributes:
      label: 为什么需要此功能？
      description: 请说明此功能解决了什么问题，或提供了什么价值。请提供具体的用例和场景，帮助我们理解其重要性。
      placeholder: |
        目前我遇到...
        如果有了此功能，我可以...
        这将为用户带来...
    validations:
      required: true      

  - type: dropdown
    id: category
    attributes:
      label: 功能类别
      description: 这个功能属于哪个类别？
      options:
        - 日历功能
        - 戒期显示
        - 用户界面
        - 移动端适配
        - 设置选项
        - 数据导入/导出
        - 其他
    validations:
      required: true


  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 清晰简洁地描述你考虑过的任何替代解决方案或功能
      placeholder: 我也考虑过...
    validations:
      required: false  

  - type: dropdown
    id: priority
    attributes:
      label: 优先级建议
      description: 你认为这个功能的重要程度如何？
      options:
        - 高 - 核心功能缺失
        - 中 - 明显改善体验
        - 低 - 锦上添花
    validations:
      required: false


  - type: textarea
    id: additional
    attributes:
      label: 补充信息
      description: 添加任何其他关于此功能请求的上下文信息
      placeholder: 其他相关信息...

  - type: checkboxes
    id: confirmation
    attributes:
      label: 确认
      description: 确保已满足以下先决条件。
      options:
        - label: 我已阅读并遵循了 `README.md` 中的所有说明。
          required: true
        - label: 我正在使用 tabloving/SK_Calendar 的最新版本。
          required: true
        - label: 我已提供我能够提供的尽可能多的相关信息，包括用例和场景。
          required: true
        - label: 我理解功能请求的实现取决于项目优先级和资源。
          required: true
          
  - type: markdown
    attributes:
      value: |
        ## 注意
        如果功能请求不完整或不遵循说明，则可能不会得到处理。请确保您已提供所有必要信息以便我们理解您的建议。
        感谢您为 tabloving/SK_Calendar 做出贡献！